# Generated by Django 2.2.7 on 2019-12-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('author', 'Can read all books')]},
        ),
    ]
